// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFrVqNL5JUu2RshM95pbVl_m1PlJwoc40',
    appId: '1:1018227670295:web:48b83e6a9091c2926acb52',
    messagingSenderId: '1018227670295',
    projectId: 'flutterweb-dd167',
    authDomain: 'flutterweb-dd167.firebaseapp.com',
    storageBucket: 'flutterweb-dd167.firebasestorage.app',
    measurementId: 'G-5X23D7DRSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGh4iOvHllgiEKSlEzioI9zZzA_oD3tlM',
    appId: '1:1018227670295:android:33a0d50621b64d976acb52',
    messagingSenderId: '1018227670295',
    projectId: 'flutterweb-dd167',
    storageBucket: 'flutterweb-dd167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Rerp795oWK3AC2M1nsBmSFWX_m51-yo',
    appId: '1:1018227670295:ios:0ba536f1c892c6206acb52',
    messagingSenderId: '1018227670295',
    projectId: 'flutterweb-dd167',
    storageBucket: 'flutterweb-dd167.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Rerp795oWK3AC2M1nsBmSFWX_m51-yo',
    appId: '1:1018227670295:ios:0ba536f1c892c6206acb52',
    messagingSenderId: '1018227670295',
    projectId: 'flutterweb-dd167',
    storageBucket: 'flutterweb-dd167.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFrVqNL5JUu2RshM95pbVl_m1PlJwoc40',
    appId: '1:1018227670295:web:ae1e1789882faae16acb52',
    messagingSenderId: '1018227670295',
    projectId: 'flutterweb-dd167',
    authDomain: 'flutterweb-dd167.firebaseapp.com',
    storageBucket: 'flutterweb-dd167.firebasestorage.app',
    measurementId: 'G-GP0DE821XY',
  );
}
